@startuml

start
while (do forever)
:Kafka **edge-to-core** topic
- **consumer.on('message', ...)**
- parse event message;
:extract event data;
:form CDT operations
- Increment campaign counter
- Increment Source counter
- Read results;
:Aerospike **operate()** to **core-aerospikedb**;
endwhile
stop

@enduml