@startuml
skinparam componentStyle uml2

package "Core Aerospike" {
    () "3000" as ascSocket
    component "Aerospike\nEnterprise\nEdition\n\nin CP mode" as asCore
    ascSocket - asCore
    database "Campaign Datastore\nAerospike CP" as core #LightPink
    asCore -r(0- core
}

@enduml