@startuml
skinparam componentStyle uml2

package "Edge Aerospike" {
    () "3010" as aseSocket
    component "Aerospike\nEnterprise\nEdition\n\nin AP mode" as asEdge
    aseSocket - asEdge
    database "Event Datastore\nAerospike AP" as edgeEUuk #LightPink
    asEdge -r(0- edgeEUuk
    
    () "8080" as asOutbound
    component [Aerospike\nOutbound Kafka\nConnector] as asKafka
    asOutbound - asKafka
    asEdge ..> asOutbound: HTTP(s)
}


@enduml