@startuml
!includeurl https://raw.githubusercontent.com/helipilot50/real-time-reporting-aerospike-kafka/master/architecture/core-component-detail.puml!0
!includeurl https://raw.githubusercontent.com/helipilot50/real-time-reporting-aerospike-kafka/master/architecture/kafka-component-detail.puml!0
!includeurl https://raw.githubusercontent.com/helipilot50/real-time-reporting-aerospike-kafka/master/architecture/aggregator-reducer-component-detail.puml!0


asNodeKafka .r.> kafClient: subscription message
asNodeKafka <.r. kafClient: event message
asNodeCore ..> ascSocket

@enduml